import type { Metadata } from "next";
import { Inter, Paytone_One, Lexend } from "next/font/google";
import ThemeProvider from "./providers";
import "./globals.css";

const payton = Paytone_One({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-payton",
});
const lexend = Lexend({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lexend",
});

export const metadata: Metadata = {
  title: "Cooky",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${lexend.variable} ${payton.variable} dark:bg-dark-0 h-full min-w-[375px]`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
